### PR TITLE
Fix PR Links and Duplicate PRs in Features and Enhancements

### LINKED ISSUE #18: Observations from testing the Endpoint release notes option
The link to Endpoint PRs at the end of PR descriptions isn't entirely correct. The attribute that's placed before the PR number ([`kib-pull`](https://github.com/elastic/docs/blob/aacf6ef23d086946375db68f625d97609765dc3c/shared/attributes.asciidoc#L528)) creates a link to PRs in the Kibana repo, when it should be creating a link to PRs in the Endpoint repo. 

Screenshot 2024-08-08 at 10 28 45 AM

### LINKED ISSUE #20: PRs are duplicated between sections in the generated ASCII
Some PRs will appear in multiple sections even though they have a single `release_note:x` label. This doesn't occur in the preview, only in the generated ASCII

### PR DESCRIPTION
**Pull request by Ikuni17**
Closes #20
Closes #18 (a bug added in #14)

Generated notes for Endpoint now have the link removed since it is a private repo:

```
[discrete]
[[release-notes-8.16.0]]
=== 8.16.0

[discrete]
[[features-8.16.0]]
==== New features
* ETW Security Auditing Part I.

[discrete]
[[enhancements-8.16.0]]
==== Enhancements
* ETW Security Auditing Part I.
```

Reverts 9603d78 and 31651ff to add the links back to release note preview on private repos:

image

### CODE REVIEW

File: src/common/pr-utils/grouping.ts [hunk 1]
```diff
@@ -73,20 +73,6 @@ export function groupPrs(prs: PrItem[], options: GroupPrOptions = {}): ReleaseNo
             break;
           case 'release_note:feature':
             groups.features.push(pr);
-            // We treat the feature label slightly different, so that it will be also grouped
-            // into the enhancement category (for the "all changes list", that doesn't list
-            // features), unless it also has another release_note label on it that will then define
-            // its group.
```
Comment (Ikuni17) [inline src/common/pr-utils/grouping.ts:79]: @nastasha-solomon This was the cause of the duplicate PRs in `features` and `enhancements` and looks be intentional. I'm guessing this is no longer needed for a "all changes list", but want to double check before merging.

**Review by nastasha-solomon — APPROVED** [review]

File: src/common/pr-utils/grouping.ts (hunk 1 above)
Comment (nastasha-solomon) [reply src/common/pr-utils/grouping.ts:79]: Hm, it might have been put in place to meet the use case requirements of the Kibana docs team. I'm fairly certain we don't need this for Security, so feel free to remove or revert it.

Comment (Ikuni17) [reply src/common/pr-utils/grouping.ts:79]: Do you know who would know if this is needed for Kibana release notes?

Comment (jbudz) [reply src/common/pr-utils/grouping.ts:79]: @lcawl

**Review by mistic — APPROVED** [review]
lgtm

File: src/common/pr-utils/grouping.ts (hunk 1 above)
Comment (lcawl) [reply src/common/pr-utils/grouping.ts:79]: This sounds like it's related to the way there's a separate "feature" list specifically for the minor releases (e.g. https://www.elastic.co/guide/en/kibana/current/release-notes-8.15.0.html and https://www.elastic.co/guide/en/kibana/current/enhancements-and-bug-fixes-v8.15.0.html)

Comment (nastasha-solomon) [reply src/common/pr-utils/grouping.ts:79]: @lcawl I'm leaning towards asking that this logic be removed. It doesn't seem as though the Kibana or Security release notes need it, and it adds to the overall effort that it takes to draft up release notes. If any PRs are mislabeled as new features, I think it makes more sense to handle them manually instead of auto-duplicating them in the asciidoc output that the tool generates.

Comment (lcawl) [reply src/common/pr-utils/grouping.ts:79]: Yes, I don't know the history of why it was decided to do this, but I agree its usefulness is questionable and ought to be revisited as part of the IA workgroup looking at release notes (@benironside @KOTungseth )

Comment (Ikuni17) [reply src/common/pr-utils/grouping.ts:79]: I've merged the PR, but feel free to comment. It is an easy revert if this behavior is needed, or we can make it easier to handle multiple use cases.
